import fs from 'fs';
let html = fs.readFileSync('index.html', 'utf8');

const mapCss = `
  /* ====== TELA MAPA ====== */
  .map-screen { padding: 0 !important; overflow: hidden; background: #0b1121; justify-content: flex-start; }
  .map-header { 
    display: flex; justify-content: flex-end; align-items: center;
    padding: 15px 24px; background: var(--bg-mid); width: 100%;
    border-bottom: 2px solid var(--grid); z-index: 10; flex-shrink: 0;
  }
  .map-stat { font-family: 'Press Start 2P'; font-size: 14px; color: var(--warn); display: flex; align-items: center; gap: 8px; }
  
  .map-scroll-area {
    width: 100%; flex: 1; overflow-y: auto; overflow-x: hidden;
    padding-bottom: 90px;
    background-image: radial-gradient(ellipse at 50% 50%, rgba(0,240,255,0.03), transparent 60%);
  }
  .map-section { width: 100%; max-width: 600px; margin: 0 auto 50px auto; }
  .map-section-header {
    color: #000; padding: 16px 20px; text-align: center;
    border-radius: 12px; margin: 24px; box-shadow: 0 4px 15px rgba(0,0,0,0.4);
  }
  .map-section-header h3 { font-family: 'Press Start 2P', monospace; font-size: 14px; margin-bottom: 8px; }
  .map-section-header p { font-family: 'VT323', monospace; font-size: 22px; margin: 0; }
  
  .map-path { display: flex; flex-direction: column; align-items: center; gap: 40px; padding: 20px 0; position: relative; }
  
  .map-node {
    width: 80px; height: 80px; border-radius: 50%;
    background: #2a3441; border: 4px solid #1a2332;
    display: flex; align-items: center; justify-content: center;
    cursor: pointer; position: relative; z-index: 2;
    transition: transform 0.2s; box-shadow: 0 8px 0 #0d131f;
  }
  .map-node:active { transform: translateY(8px); box-shadow: 0 0 0 #0d131f; }
  .map-node.done { background: var(--hero-cyan); border-color: #fff; box-shadow: 0 8px 0 #008899; }
  .map-node.current { background: var(--warn); border-color: #fff; box-shadow: 0 8px 0 #cc9900; animation: pulseNode 1.5s infinite; }
  .map-node.locked { opacity: 0.6; cursor: not-allowed; }
  .map-node:active.locked { transform: none; box-shadow: 0 8px 0 #0d131f; }
  .map-node img { width: 54px; height: 54px; border-radius: 50%; object-fit: cover; border: 2px solid rgba(255,255,255,0.5); }
  .map-node .locked-icon { font-size: 30px; opacity: 0.5; }
  
  /* SVG path connection */
  .map-path svg { position: absolute; top: 0; left: 0; width: 100%; height: 100%; pointer-events: none; z-index: 1; }
  
  @keyframes pulseNode {
    0% { transform: scale(1); box-shadow: 0 8px 0 #cc9900; }
    50% { transform: scale(1.05); box-shadow: 0 8px 0 #cc9900, 0 0 20px rgba(255,207,58,0.5); }
    100% { transform: scale(1); box-shadow: 0 8px 0 #cc9900; }
  }

  .map-navbar {
    position: absolute; bottom: 0; left: 0; right: 0;
    height: 70px; background: var(--bg-mid); border-top: 2px solid var(--grid);
    display: flex; justify-content: space-around; align-items: center; z-index: 10;
  }
  .map-nav-item {
    background: transparent; border: none; font-size: 28px;
    cursor: pointer; padding: 10px; transition: all 0.2s; filter: grayscale(1); opacity: 0.5;
  }
  .map-nav-item.active { filter: grayscale(0); opacity: 1; transform: scale(1.1); }
  .map-nav-item span { pointer-events: none; }
  
  /* Hide the old villain select screen */
  #screen-villain { display: none !important; }
`;

html = html.replace('/* ====== TELA TÍTULO ====== */', mapCss + '\n  /* ====== TELA TÍTULO ====== */');

const mapHtml = `
  <!-- ====== TELA MAPA ====== -->
  <section class="screen map-screen" id="screen-map">
    <div class="map-header">
      <div class="map-stat">⭐ <span id="map-score-display">0</span></div>
    </div>
    
    <div class="map-scroll-area" id="map-container">
      <!-- Generated by JS -->
    </div>
    
    <div class="map-navbar">
      <button class="map-nav-item active" onclick="go('map')">🗺️</button>
      <button class="map-nav-item" onclick="go('rank')">🏆</button>
    </div>
  </section>
`;

html = html.replace('<!-- ====== SELEÇÃO DE HERÓI ====== -->', mapHtml + '\n  <!-- ====== SELEÇÃO DE HERÓI ====== -->');

const mapJs = `
// ====== ESTADO DO PROGRESSO ======
const userProgress = {
  unlockedNodes: ['sepzilla'],
  completedNodes: [],
  score: 0
};

const MAP_DATA = [
  {
    id: 'sec1',
    title: 'SEÇÃO 1',
    subtitle: 'Navegue pelas IRAS',
    color: '#00f0ff',
    bg: '#0a8aa6',
    nodes: [
      { id: 'sepzilla', type: 'villain' },
      { id: 'pseudomor', type: 'villain' },
      { id: 'escherika', type: 'villain' },
      { id: 'tubotox', type: 'villain' },
      { id: 'klebzor', type: 'villain' },
      { id: 'cateterion', type: 'villain' },
      { id: 'staphurion', type: 'villain' }
    ]
  },
  {
    id: 'sec2',
    title: 'SEÇÃO 2',
    subtitle: 'Precauções de Contato',
    color: '#ffcf3a',
    bg: '#cc9900',
    nodes: [
      { id: 'locked_1', type: 'locked' },
      { id: 'locked_2', type: 'locked' },
      { id: 'locked_3', type: 'locked' }
    ]
  },
  {
    id: 'sec3',
    title: 'SEÇÃO 3',
    subtitle: 'Segurança do Paciente',
    color: '#ff4d6d',
    bg: '#cc0033',
    nodes: [
      { id: 'locked_4', type: 'locked' },
      { id: 'locked_5', type: 'locked' }
    ]
  }
];

function buildMap() {
  const container = $('#map-container');
  container.innerHTML = '';
  $('#map-score-display').innerText = userProgress.score;
  
  MAP_DATA.forEach(section => {
    const secDiv = document.createElement('div');
    secDiv.className = 'map-section';
    
    // Header
    secDiv.innerHTML += \`
      <div class="map-section-header" style="background: \${section.color}">
        <h3 style="color: \${section.bg}">\${section.title}</h3>
        <p style="color: #000"><b>\${section.subtitle}</b></p>
      </div>
    \`;
    
    const pathDiv = document.createElement('div');
    pathDiv.className = 'map-path';
    
    // Create an SVG to draw lines between nodes
    const svgId = 'svg-' + section.id;
    pathDiv.innerHTML = \`<svg id="\${svgId}"></svg>\`;
    
    const nodeElements = [];
    const offsets = [0, 40, 60, 40, 0, -40, -60, -40];
    
    section.nodes.forEach((node, idx) => {
      const xOffset = offsets[idx % offsets.length];
      
      const isDone = userProgress.completedNodes.includes(node.id);
      let isCurrent = false;
      let isLocked = true;
      
      if (node.type !== 'locked') {
        const nodeIndex = section.nodes.findIndex(n => n.id === node.id);
        const prevNodeId = nodeIndex > 0 ? section.nodes[nodeIndex-1].id : null;
        
        if (isDone) {
          isLocked = false;
        } else if (nodeIndex === 0 || (prevNodeId && userProgress.completedNodes.includes(prevNodeId))) {
          isCurrent = true;
          isLocked = false;
        }
      }
      
      let stateClass = 'locked';
      if (isDone) stateClass = 'done';
      if (isCurrent) stateClass = 'current';
      
      const nodeEl = document.createElement('div');
      nodeEl.className = \`map-node \${stateClass}\`;
      nodeEl.style.transform = \`translateX(\${xOffset}px)\`;
      
      if (node.type === 'villain') {
        const v = VILLAINS[node.id];
        let imgHtml = '';
        if (isLocked) {
          imgHtml = \`<span class="locked-icon">🔒</span>\`;
        } else {
           const match = SPRITES[node.id].match(/src="(.*?)"/);
           const src = match ? match[1] : '';
           imgHtml = \`<img src="\${src}" />\`;
        }
        nodeEl.innerHTML = imgHtml;
        
        nodeEl.addEventListener('click', () => {
          if (!isLocked) {
             nodeEl.style.transform = \`translateX(\${xOffset}px) scale(0.9)\`;
             setTimeout(() => {
                nodeEl.style.transform = \`translateX(\${xOffset}px)\`;
                state.villain = v;
                go('hero');
             }, 150);
          }
        });
      } else {
         nodeEl.innerHTML = \`<span class="locked-icon">🔒</span>\`;
         nodeEl.addEventListener('click', () => {
           if (!nodeEl.classList.contains('locked')) return;
           nodeEl.style.transform = \`translateX(\${xOffset}px) scale(0.9)\`;
           setTimeout(()=>{
             nodeEl.style.transform = \`translateX(\${xOffset}px)\`;
           }, 150);
         });
      }
      
      nodeElements.push({ el: nodeEl, xOffset: xOffset });
      pathDiv.appendChild(nodeEl);
    });
    
    secDiv.appendChild(pathDiv);
    container.appendChild(secDiv);
  });
}
`;

html = html.replace('// ====== LÓGICA DE AUTH E RANKING (SUPABASE) ======', mapJs + '\n\n// ====== LÓGICA DE AUTH E RANKING (SUPABASE) ======');

let oldLoginSuccess = `     currentUser = data.user;
      go('title');`;
let newLoginSuccess = `     currentUser = data.user;
      buildMap();
      go('map');`;

html = html.replace(oldLoginSuccess, newLoginSuccess);

let oldLogout = `      currentUser = null;
      document.getElementById('ranking-body').innerHTML = ''; // Limpa ranking
      go('auth');`;
let newLogout = `      currentUser = null;
      document.getElementById('ranking-body').innerHTML = ''; // Limpa ranking
      go('auth');`;
      
let oldMenuButton = `$$('[data-back]').forEach(b => b.addEventListener('click', e => go(e.target.dataset.back)));`;
let newMenuButton = `$$('[data-back]').forEach(b => b.addEventListener('click', e => {
  const target = e.target.dataset.back;
  if(target === 'title' || target === 'villain') {
    buildMap();
    go('map');
  } else {
    go(target);
  }
}));`;
html = html.replace(oldMenuButton, newMenuButton);

let oldInitBtn = `document.getElementById('btn-start').addEventListener('click', () => {
  if (currentUser) {
    go('hero');
  } else {
    go('auth');
  }
});`;
let newInitBtn = `document.getElementById('btn-start').addEventListener('click', () => {
  if (currentUser) {
    buildMap();
    go('map');
  } else {
    go('auth');
  }
});`;
html = html.replace(oldInitBtn, newInitBtn);

let oldVictory = `if(acc >= qTotal) {`;
let newVictory = `if(acc >= qTotal) {
      if(!userProgress.completedNodes.includes(state.villain.id)) {
         userProgress.completedNodes.push(state.villain.id);
      }
      userProgress.score += totalScore;
`;
html = html.replace(oldVictory, newVictory);

fs.writeFileSync('index.html', html, 'utf8');
